### ISSUE TITLE
How to compile for use in the browser without nodejs?

### ISSUE THREAD

**Issue by guest271314** [abbr/text2wav.node.js#1]
How to create a standalone version that is not dependent on `nodejs` for use in the browser?

**Comment by abbr** [comment]
Change [NODEFS](https://github.com/abbr/text2wav.node.js/blob/186a27941e4f02cf8282ec1409f66f3fef504ca7/lib/post.js#L3) to IDBFS.

**Comment by guest271314** [comment]
Am actually trying to modify the existing code without running emscripten to compile or nodejs. Is that possible?
