### ISSUE TITLE
Sounds are not very clear

### ISSUE THREAD

**Issue by idoor88** [abbr/text2wav.node.js#2]
I tried to run the lib with

var text = "Good Morning, friends, how are you."; 
	console.log(" text: ", text);
	let out1 = await text2wav('测试', {voice: 'zh'});
	console.log(" out1: ", out1);
	fs.writeFileSync("testch.wav", Buffer.from(out1.buffer));
	let txtWav = await text2wav(text); 
	console.log(" txtWav: ", txtWav);

	fs.writeFileSync("testfile.wav", Buffer.from(txtWav.buffer));

then I play the wav files, both played ok, but both the sounds are not clear, anyway to configure the lib to make the sounds more accurate?

Thanks

**Comment by joy-mollick** [comment]
> I tried to run the lib with
> 
> var text = "Good Morning, friends, how are you."; console.log(" text: ", text); let out1 = await text2wav('测试', {voice: 'zh'}); console.log(" out1: ", out1); fs.writeFileSync("testch.wav", Buffer.from(out1.buffer)); let txtWav = await text2wav(text); console.log(" txtWav: ", txtWav);
> 
> ```
> fs.writeFileSync("testfile.wav", Buffer.from(txtWav.buffer));
> ```
> 
> then I play the wav files, both played ok, but both the sounds are not clear, anyway to configure the lib to make the sounds more accurate?
> 
> Thanks

How did you get this managed ?? Urgent help please
